#!/usr/bin/env node
/**
 * Generates .env from a Firebase service-account JSON file.
 *
 *   npm run setup                       -- auto-find the downloaded JSON
 *   npm run setup -- path/to/key.json   -- point at it explicitly
 *
 * Handles the part that's easy to get wrong by hand: the private key must
 * land in .env as a single quoted line with literal \n sequences, which is
 * exactly what server/firebase.js expects to unescape at startup.
 */
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env');

const args = process.argv.slice(2);
const force = args.includes('--force');
const explicitPath = args.find((a) => !a.startsWith('--'));

function fail(msg) {
  console.error('\n  ✗ ' + msg + '\n');
  process.exit(1);
}

// A service-account JSON is named like:
//   <project>-firebase-adminsdk-<hash>.json
// Look in the project folder first, then the usual download locations.
function findServiceAccountJson() {
  const dirs = [
    ROOT,
    path.join(os.homedir(), 'Downloads'),
    path.join(os.homedir(), 'Desktop'),
    os.homedir(),
  ];
  const hits = [];
  for (const dir of dirs) {
    let names = [];
    try {
      names = fs.readdirSync(dir);
    } catch {
      continue;
    }
    for (const name of names) {
      if (!name.endsWith('.json')) continue;
      if (!/firebase[-_]?adminsdk|serviceaccount/i.test(name)) continue;
      const full = path.join(dir, name);
      try {
        hits.push({ full, mtime: fs.statSync(full).mtimeMs });
      } catch {}
    }
  }
  // Newest first — if they've regenerated the key, that's the live one.
  hits.sort((a, b) => b.mtime - a.mtime);
  return hits.length ? hits[0].full : null;
}

const jsonPath = explicitPath
  ? path.resolve(explicitPath)
  : findServiceAccountJson();

if (!jsonPath) {
  fail(
    'Could not find a Firebase service-account JSON file.\n\n' +
      '    Download one from the Firebase console:\n' +
      '      Project settings > Service accounts > Generate new private key\n\n' +
      '    Then either leave it in your Downloads folder and re-run this,\n' +
      '    or pass the path:  npm run setup -- C:\\path\\to\\key.json'
  );
}

if (!fs.existsSync(jsonPath)) {
  fail('No such file: ' + jsonPath);
}

let sa;
try {
  sa = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
} catch (e) {
  fail('That file is not valid JSON: ' + jsonPath + '\n    ' + e.message);
}

for (const field of ['project_id', 'client_email', 'private_key']) {
  if (!sa[field]) {
    fail(
      'That JSON file is missing "' + field + '".\n\n' +
      '    It does not look like a service-account key. Make sure you used\n' +
      '    "Generate new private key" on the Service accounts tab, not the\n' +
      '    google-services.json / firebaseConfig snippet used by client apps.'
    );
  }
}

if (fs.existsSync(ENV_PATH) && !force) {
  fail(
    '.env already exists — not overwriting it.\n\n' +
      '    Re-run with:  npm run setup -- --force\n' +
      '    (or delete .env first)'
  );
}

// Buckets created since Oct 2024 are <project>.firebasestorage.app; older
// projects use <project>.appspot.com. Default to the modern form and tell
// the user how to confirm, since guessing wrong is a silent 404 later.
const bucket =
  process.env.FIREBASE_STORAGE_BUCKET || sa.project_id + '.firebasestorage.app';

// Re-escape real newlines back to literal \n for .env storage.
const privateKeyEscaped = sa.private_key.replace(/\n/g, '\\n');

// Generated rather than left as a placeholder — a default admin password on
// a public URL is the most likely way this site gets tampered with.
const adminPassword = crypto.randomBytes(12).toString('base64url');

const env = `# Generated by "npm run setup" on ${new Date().toISOString()}
# Source: ${jsonPath}
# This file contains secrets. It is gitignored — keep it that way.

PORT=3000

FIREBASE_PROJECT_ID=${sa.project_id}
FIREBASE_CLIENT_EMAIL=${sa.client_email}
FIREBASE_PRIVATE_KEY="${privateKeyEscaped}"
FIREBASE_STORAGE_BUCKET=${bucket}

ADMIN_USER=admin
ADMIN_PASSWORD=${adminPassword}
`;

fs.writeFileSync(ENV_PATH, env, { mode: 0o600 });

console.log('\n  ✓ Wrote .env');
console.log('    from  ' + jsonPath);
console.log('\n  Your admin login (save this somewhere):');
console.log('    user      admin');
console.log('    password  ' + adminPassword);
console.log('\n  Storage bucket guessed as:');
console.log('    ' + bucket);
console.log(
  '    If the Storage page in the Firebase console shows a different name\n' +
    '    (older projects end in .appspot.com), edit FIREBASE_STORAGE_BUCKET in .env.'
);
console.log('\n  Next:  npm run check\n');
